name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:      
  train-dev:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit job
      run: |
        az ml job create --file src/dev_job.yml --workspace-name "wkspace_int_preps" --resource-group "prep_interviews" --stream
  train-prd:
    needs: dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit job
      run: |
        az ml job create --file src/prod_job.yml --workspace-name "wkspace_int_preps" --resource-group "prep_interviews" --stream