name: Trigger on Pull Request

on:
  pull_request:
      branches:
      - main
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Lint with flake8
      run: |
        pip install flake8 && flake8 .
    - name: Test with pytest
      run: |
        pytest